# Generated by Django 3.2.8 on 2021-10-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaani', '0002_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
