# Generated by Django 3.2.8 on 2021-10-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaani', '0003_neighbourhood_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
